export enum CandidateEnum {
    COMUM = "COMUM",
    VEREADOR = "VEREADOR",
    PREFEITO = "PREFEITO",
    ESTADUAL = "ESTADUAL",
    FEDERAL = "FEDERAL",
    GOVERNADOR = "GOVERNADOR",
    SENADOR = "SENADOR",
    PRESIDENTE = "PRESIDENTE"
}