export enum ConfigEnvEnum {
    GOOGLE_CLOUD_STORAGE_CLIENT_EMAIL = 'GOOGLE_CLOUD_STORAGE_CLIENT_EMAIL',
    GOOGLE_CLOUD_STORAGE_PRIVATE_KEY = 'GOOGLE_CLOUD_STORAGE_PRIVATE_KEY',
    GOOGLE_CLOUD_STORAGE_PROJECT_ID = 'GOOGLE_CLOUD_STORAGE_PROJECT_ID',
    GOOGLE_CLOUD_STORAGE_STORAGE_BUCKET = 'GOOGLE_CLOUD_STORAGE_STORAGE_BUCKET'
}